#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=16
# run step 1 to step 5 by default
stage=1
stop_stage=5

# We assume dl_dir (download dir) contains the following directories and files.
#
#  - $dl_dir/GigaSpeech2

subset_name=pool5_8
dl_dir=$PWD/download/ssl_$subset_name
manifest_dir=data/manifest_$subset_name
fbank_dir=data/ssl_$subset_name
lang=Vietnam
num_per_split=200000

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

log "dl_dir: $dl_dir"

# subsets=""
# for dir in ${dl_dir}/pool4/* ; do
#   subset=$(basename $dir)
#   subsets="$subsets $subset"
# done
# log "Find subsets: $subsets"


if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare GigaSpeech2 manifest, language: $lang"
  # We assume that you have downloaded the GigaSpeech2 corpus
  # to $dl_dir/GigaSpeech2
  mkdir -p $manifest_dir
  if [ ! -e $manifest_dir/.gigaspeech2.done ]; then
    # lhotse prepare gigaspeech2 --lang $lang -j $nj $dl_dir/pool4 $manifest_dir
    python local/gigaspeech2_ssl.py --lang $lang -j $nj $dl_dir $subset_name $manifest_dir
    touch $manifest_dir/.gigaspeech2.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "State 2: Preprocess GigaSpeech2 manifest"
  if [ ! -f $fbank_dir/.preprocess.done ]; then
   python3 ./local/preprocess_gigaspeech2_ssl.py --lang $lang --dataset "$subset_name" --src-dir $manifest_dir --tgt-dir $fbank_dir
   touch $fbank_dir/.preprocess.done
  fi
fi

# if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
#   log "Stage 3: Compute fbank for test set"
#   mkdir -p $fbank_dir
#   ./local/compute_fbank_gigaspeech2.py
# fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Split train set into pieces"
  log "Split subset: $subset_name"
  split_dir=$fbank_dir/${subset_name}_split
  if [ ! -f $split_dir/.split.done ]; then
    lhotse split-lazy $fbank_dir/gigaspeech2-ssl_cuts_${subset_name}_raw.jsonl.gz $split_dir $num_per_split
    touch $split_dir/.split.done
  fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 5: Compute features for train set"
  python local/compute_fbank_gigaspeech2_ssl_splits.py parallel --src-dir $fbank_dir --dataset $subset_name
fi

